version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql_server_prod
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PasswordFuerte123!
    ports:
      - "1433:1433"

  backend:
    build:
      context: ./IncidentesApi
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=IncidentesDb;User Id=sa;Password=PasswordFuerte123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./IncidentesFront
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend